# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"  # 9
  hostname = "kb-debian-stretch64"
  config.vm.hostname = hostname

  # Settings for Virtualbox
  config.vm.provider "virtualbox" do |vb|
     vb.linked_clone = true
     vb.name = hostname
  end

  config.vm.provision "shell", path: "dependencies.sh", name: "dependencies"
  config.vm.provision "shell", path: "setup.sh", privileged: false
end
